# Generated by Django 2.1.7 on 2020-08-26 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Grupo',
            },
        ),
        migrations.CreateModel(
            name='Jovens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='images', verbose_name='Foto')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone - Ex: 11948924982')),
                ('presenca', models.CharField(choices=[('SIM', 'SIM'), ('NÃO', 'NÃO')], default='NÃO', max_length=3, verbose_name='Está na Reunião?')),
                ('data', models.DateField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Jovens',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_Jovem', models.IntegerField()),
                ('data', models.DateField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Relatorio',
            },
        ),
        migrations.CreateModel(
            name='RelatorioAlgoAMais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_Jovem', models.IntegerField()),
                ('reuniao', models.CharField(default='Encontro Jovem', max_length=20, verbose_name='Reunião')),
                ('data', models.DateField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Relatorio Algo A +',
            },
        ),
        migrations.CreateModel(
            name='RelatorioEncontroJovem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt_Jovem', models.IntegerField()),
                ('reuniao', models.CharField(default='Algo A +', max_length=20, verbose_name='Reunião')),
                ('data', models.DateField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo')),
            ],
            options={
                'verbose_name_plural': 'Relatorio Encontro Jovem',
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reuniao', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Reunião',
            },
        ),
        migrations.CreateModel(
            name='Tribo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tribo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Tribo',
            },
        ),
        migrations.AddField(
            model_name='relatorioencontrojovem',
            name='tribo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tribo'),
        ),
        migrations.AddField(
            model_name='relatorioalgoamais',
            name='tribo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tribo'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='reuniao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Reuniao'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='tribo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tribo'),
        ),
        migrations.AddField(
            model_name='jovens',
            name='tribo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tribo'),
        ),
    ]
