# Generated by Django 3.1 on 2020-10-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jovensnaopresente',
            name='foto_base64',
        ),
    ]
