# Generated by Django 3.1 on 2020-10-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jovens',
            name='foto_base64',
            field=models.CharField(max_length=2000000000000000),
        ),
    ]
